ziri-bros/high-geupsik-frontend

- src/component/common/BoardNavigation.jsx
- src/component/common/Header.jsx
- src/component/common/HeaderNavigation.jsx
- src/page/Board.jsx
- src/routes/index.jsx
1. 게시판 페이지(Board) 라우터 추가
2. 헤더 하이급식 아이콘 라우터 추가
3. 보드네비게이션 추가
> [FEAT] 게시판 네비게이션

- src/component/AdminController.jsx
- src/component/Timetable.jsx
- src/component/common/Modal.jsx
사용 예시 : <Modal title="시간표를 모두 지우시겠습니까?" onCancel={onCancel} onConfirm={onConfirm} />
상세 설명 
1. title : 모달 창 제목
2. onCancel : 모달 창 취소 클릭 시 호출 되는 함수
3. onConfirm : 모달 창 확인 클릭 시 호출 되는 함수
> [FEAT]: Modal 공통 컴포넌트로 분리

- src/component/common/Preview.jsx
- src/page/HomePage.jsx
- src/page/SchoolFoodPage.jsx
- src/routes/index.jsx
날짜 넘김 시, 페이지 드래그식 UI구현 (캐러셀) 제외한 이슈
> [FEAT] 급식 페이지 #35

- src/component/common/BoardComponent.jsx
- src/component/common/BoardNotice.jsx
- src/component/common/BoardPosting.jsx
- src/component/common/Preview.jsx
- src/page/HomePage.jsx
> [FIX] 담당영역 UI/UX 및 기타 수정사항 #36

- src/component/MyInfo.jsx
- src/component/MyInfoDetail.jsx
- src/component/Post.jsx
- src/component/PostCreate.jsx
- src/component/common/Button.jsx
- src/component/common/CommentInput.jsx
> [FIX] 게시글 댓글 달기, 게시글 작성 UI 수정

- src/component/AdminController.jsx
- src/component/MyInfo.jsx
- src/lib/api/admin.jsx
> [Fix] API response data 이름 변경

- src/component/MyInfoDetail.jsx
- src/lib/api/auth.jsx
> [FEAT] 내정보 수정 API 연동

- .eslintrc.js
- src/component/Comment.jsx
- src/component/Post.jsx
- src/component/PostCreate.jsx
- src/component/common/CommentInput.jsx
- src/component/common/DropDown.jsx
- src/component/common/MoreButtonPop.jsx
- src/lib/api/admin.jsx
- src/lib/api/auth.jsx
- src/lib/api/board.jsx
- src/lib/api/comment.jsx
- src/page/PostPage.jsx
- src/utils/parseTime.jsx
대댓글은 아직 API 연동 안됐음
아직 전체적으로 미완성
> [FEAT] 상세게시글, 댓글 컴포넌트 API 연동

- src/component/AdminController.jsx
> [Feat] 학생증 승인/거절버튼 클릭 시, 학생증 리스트 자동 렌더링

- src/component/MyInfoDetail.jsx
- src/component/common/Button.jsx
> [Fix] 버튼 컴포넌트 높이 맞추기 in 시간표, 내정보페이지

- src/component/MyInfoDetail.jsx
- src/component/Timetable.jsx
- src/component/common/DropDown.jsx
> [FEAT] 학년 및 반 필드 추가 in 입력, 내정보 수정페이지

- src/component/common/HeaderWrapper.jsx
- src/page/AdminPage.jsx
- src/page/AuthPage.jsx
- src/page/BoardPage.jsx
- src/page/HomePage.jsx
- src/page/MatchPage.jsx
- src/page/MyInfoDetailPage.jsx
- src/page/MyInfoPage.jsx
- src/page/PostCreatePage.jsx
- src/page/PostEditPage.jsx
- src/page/PostPage.jsx
- src/page/SchedulePage.jsx
- src/page/SchoolFoodPage.jsx
> [FIX] 헤더 내비게이션 흔들림 수정

- src/constants/index.jsx
- src/page/BoardPage.jsx
- src/page/PostEditPage.jsx
- src/page/PostPage.jsx
> [FIX] 보더 네비게이션 게시판 흔들림 수정

- src/component/Timetable.jsx
> [FIX] 시간표 조회 API 연동시, 반환데이터 유무 체크함수 추가

- src/component/Post.jsx
- src/component/common/BoardNavigation.jsx
- src/component/common/HeaderNavigation.jsx
- src/page/PostPage.jsx
> [FEAT] 페이지별 접속시 헤더 내비게이션, 보더 내비게이션 강조

- .gitignore
> [CHORE] gitignore 수정

- .env.development
- .gitignore
> [Chore] gitignore 다시 적용

- src/component/Cocomment.jsx
- src/component/Comment.jsx
- src/component/Post.jsx
> [FEAT] 댓글 작성자 구분 및 명시

- src/component/Post.jsx
- src/component/common/HeaderNavigation.jsx
> [FIX] 헤더 내비게이션 함수 수정, 게시글 사진 사이즈 변경

- src/component/common/BoardComponent.jsx
> [FEAT] 게시글 컴포넌트 카테고리 한글화

- src/component/Post.jsx
> [STYLE] 댓글 입력 창 밑으로 고정

- src/component/common/Button.jsx
> [Style] 시간표 > 저장하기 버튼 디자인 변경

- src/component/Post.jsx
- src/component/common/BoardComponent.jsx
- src/lib/api/board.jsx
> [FIX] 인기게시판 API 수정, 조회수 주석처리

- src/lib/api/board.jsx
> [FIX] getBoardList API 수정

- .env.development
- src/component/MyInfo.jsx
- src/component/MyScoolLink.jsx
- src/component/SchoolFood.jsx
- src/component/SchoolFoold.jsx
- src/component/common/BoardComponent.jsx
- src/component/common/Preview.jsx
- src/lib/api/schoolFoodInfo.jsx
- src/lib/api/schoolInfo.jsx
- src/page/HomePage.jsx
- src/page/SchoolFoodPage.jsx
- src/store/index.jsx
- src/store/schoolFood.jsx
- src/store/schoolFoodList.jsx
- src/utils/index.jsx
> [FEAT] 급식 페이지

- src/component/SchoolFood.jsx
> Fix: 오늘의 급식 내부 급식리스트 초기 랜더링 문제 해결

- src/component/SchoolFood.jsx
- src/component/common/BoardComponent.jsx
- src/component/common/Preview.jsx
> [FIX] BoardComponent내 view제거 & 한성과고 급식 처리

- src/component/Search.jsx
- src/component/common/History.jsx
- src/component/common/SearchBar.jsx
- src/component/common/SearchedContentsComponent.jsx
- src/lib/api/search.jsx
> [FEAT] 검색 활성화

- src/component/MatchProcedure.jsx
- src/component/MyInfoDetail.jsx
- src/component/MyScoolLink.jsx
- src/component/common/Preview.jsx
- src/constants/index.jsx
- src/lib/api/auth.jsx
> [FEAT] 학교별 정보 추가

- package.json
- src/component/Cocomment.jsx
- src/component/Comment.jsx
- src/component/Message/MessageLobby/MessageLobbyItem/index.jsx
- src/component/Message/MessageLobby/MessageLobbyItem/style.js
- src/component/Message/MessageLobby/index.jsx
- src/component/Message/MessageLobby/style.js
- src/component/Message/MessageRoom/index.jsx
- src/component/Message/MessageRoom/style.js
- src/component/MyInfo.jsx
- src/component/Notification.jsx
- src/component/Post.jsx
- src/component/common/BoardComponent.jsx
- src/component/common/MoreButtonPop.jsx
- src/hooks/useChatRoomInfiniteScroll.js
- src/hooks/useInfiniteScroll.js
- src/lib/api/board.jsx
- src/lib/api/client.js
- src/lib/api/comment.jsx
- src/lib/api/message.js
- src/lib/api/notification.jsx
- src/page/MessagePage.jsx
- src/page/MessageRoomPage.jsx
- src/routes/index.jsx
- yarn.lock
> [FEAT] 무한스크롤, 쪽지방
